### ISSUE TITLE
Don't duplicate vanilla strings

### ISSUE THREAD

**Issue by Madis0** [LambdAurora/SpruceUI#11]
**Is your feature request related to a problem? Please describe.**
SpruceUI language file seems to contain strings that don't really need to be re-translated, as they are already available in vanilla strings. Why not use them directly?

**Describe the solution you'd like**
In your mods, use these vanilla phrases instead of creating a custom one:

- spruceui.reset - mco.brokenworld.reset
- spruceui.not_bound - key.keyboard.unknown
- spruceui.options.generic.default - generator.default
- spruceui.options.generic.fancy - options.graphics.fancy
- spruceui.options.generic.fast - options.graphics.fast
- spruceui.options.generic.none - gui.none
- spruceui.options.generic.unbound - key.keyboard.unknown

**Describe alternatives you've considered**
Some strings can still be created if the context is very different, but most should still be vanilla for better compatibility with several languages.

**Additional context**
See also: #10

**Comment by LambdAurora** [comment]
Will apply those changes for 
 - `spruceui.not_bound`
 - `spruceui.options.generic.default`
 - `spruceui.options.generic.none`
 
Fancy and fast are a little too bit contextual to be changed.
 
I couldn't find anything about `mco.brokenworld.reset` in the MC language file.

`spruceui.options.generic.unbound` is the action rather than the adjective

**Comment by Madis0** [comment]
> I couldn't find anything about `mco.brokenworld.reset` in the MC language file.

Oops, that was in Realms. But I found a more closer one anyway, `controls.reset`.

**Comment by LambdAurora** [comment]
`controls.reset` has some issues, like in French, it's cut off because the original place for it is too short to have the full word.

**Comment by Madis0** [comment]
Okay, fair enough.

> spruceui.options.generic.unbound is the action rather than the adjective

Shouldn't that be "unbind" then?

**Comment by LambdAurora** [comment]
It should, my mistake
