### ISSUE TITLE
SpruceTextAreaWidgets cause a crash if clicked on without writing text into them from code

### ISSUE THREAD

**Issue by Setadokalo** [LambdAurora/SpruceUI#14]
**Describe the bug**
Adding a text area directly to a screen, without first calling `SpruceTextAreaWidget#write(String)` on it with some string, will make the game crash when the user clicks on the widget.

**To Reproduce**
1. Create a new TextAreaWidget
2. Add it to a screen
3. Launch the game, open the screen, and click into the text area
4. Game crash

**Expected behavior**
Cursor to be at the beginning of an empty line

**Version Info:**
 - OS: Linux, Debian Testing
 - Minecraft 1.16.4
 - Fabric 0.25.1+build.416-1.16
 - Mods: modmenu v1.14.6+build.31
 - Version 1.6.4

**Comment by LambdAurora** [comment]
Fixed in 2.0.0.
