### ISSUE TITLE
Deprecated ModMenu Stuff

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [LambdAurora/SpruceUI#16]
**Describe the bug**
The following is spammed in logs: `[main/WARN]: WARNING! Mod spruceui is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

**Comment by LambdAurora** [comment]
This is fixed for 1.17.

Given that users can have an older version of ModMenu in 1.16 I'm not fixing this for 1.16 or it would break for those users.
