### ISSUE TITLE
Add a way to replace vanilla main menu buttons

### ISSUE THREAD

**Issue by brunociria** [LambdAurora/SpruceUI#25]
It would be great if there was a function to replace a vanilla button with your own.

**Comment by LambdAurora** [comment]
Isn't that already possible with Fabric API/QSL's screen API?

**Comment by brunociria** [comment]
> Isn't that already possible with Fabric API/QSL's screen API?

I just started working with Fabric so i'm not familiar with the Fabric API. thank you for the feedback!
