### ISSUE TITLE
Add the required version of Spruceui to the release tab in order to download it and run the dynamic lights mod - 1.19

### ISSUE THREAD

**Issue by Yoad1704** [LambdAurora/SpruceUI#27]
**Is your feature request related to a problem? Please describe.**
Not at the UI itself, just on the Github page of it (missing the UI which I was asked to download to run the dynamic lights mod)

**Describe the solution you'd like**
Add the UI at the required version of it to run the dynamic lights mod in the releases tab

**Describe alternatives you've considered**
None

**Additional context**
None

BTW - So sry fore being pushy just want to make sure ur aware of it

**Comment by LambdAurora** [comment]
Hi, LambDynamicLights release had a little hiccup on Modrinth.

Please re-download it to fix this issue.
