### ISSUE TITLE
Build just ded

### ISSUE THREAD

**Issue by ALEKSCRAFTPLAY** [LambdAurora/SpruceUI#43]
"Just do ./gradlew build and everything should build just fine!"
nuh uh

C:\Users\ALEKS\Downloads\SpruceUI-1.20>gradlew build

> Configure project :
Fabric Loom: 1.2.7
:remapping 6 mods from modImplementation (java-api)
:remapping 1 mods from modLocalRuntime (java-runtime)
:remapping sources

> Task :checkLicenseMain FAILED
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\background\Background.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\background\DirtTexturedBackground.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\background\EmptyBackground.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\background\SimpleColorBackground.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\border\Border.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\border\EmptyBorder.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\border\SimpleBorder.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\event\EventUtil.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\event\OpenScreenCallback.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\event\ResolutionChangeCallback.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\hud\component\TextHudComponent.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\hud\Hud.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\hud\HudComponent.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\hud\HudManager.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\mixin\MinecraftClientMixin.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\navigation\NavigationDirection.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\navigation\NavigationUtils.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceBooleanOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceCheckboxBooleanOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceCyclingOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceDoubleInputOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceDoubleOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceFloatInputOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceIntegerInputOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceSeparatorOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceSimpleActionOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceStringOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\option\SpruceToggleBooleanOption.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\Position.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\screen\SpruceHandledScreen.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\screen\SpruceScreen.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\SprucePositioned.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\SpruceTexts.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\Tooltip.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\Tooltipable.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\util\ColorUtil.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\util\Identifiable.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\util\MultilineText.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\util\Nameable.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\util\RenderUtil.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\util\ScissorManager.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\util\SpruceUtil.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\AbstractSpruceBooleanButtonWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\AbstractSpruceButtonWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\AbstractSpruceIconButtonWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\AbstractSprucePressableButtonWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\AbstractSpruceWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\container\AbstractSpruceParentWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\container\SpruceContainerWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\container\SpruceEntryListWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\container\SpruceOptionListWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\container\SpruceParentWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\container\tabbed\SpruceTabbedWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\option\SpruceOptionSliderWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceButtonWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceCheckboxWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceElement.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceIconButtonWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceLabelWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceSeparatorWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceSliderWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceTexturedButtonWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceToggleSwitch.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\SpruceWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\text\AbstractSpruceTextInputWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\text\SpruceNamedTextFieldWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\text\SpruceTextAreaWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\text\SpruceTextFieldWidget.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\WithBackground.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\widget\WithBorder.java - license checks have failed.
 - C:\Users\ALEKS\Downloads\SpruceUI-1.20\src\main\java\dev\lambdaurora\spruceui\wrapper\VanillaButtonWrapper.java - license checks have failed.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkLicenseMain'.
> License header checks have failed on 72 out of 72 files.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 52s
7 actionable tasks: 7 executed

**Comment by ALEKSCRAFTPLAY** [comment]
found that the license file is not here as i checked

**Comment by ALEKSCRAFTPLAY** [comment]
nvm found the file but idk why it still not works

**Comment by cckk4467** [comment]
Did you address it? I met the same problem.
