### ISSUE TITLE
Bottom and top bars not showing in game

### ISSUE THREAD

**Issue by legoraft** [LambdAurora/SpruceUI#48]
**Describe the bug**
I tried using this amazing api for creating an option screen for my mod, but I can't get the top and bottom dirt textured bars to show up. I tried figuring things out with the test mod, but I couldn't.

The code I'm using for my screen is the following:
```java
public class configScreen extends SpruceScreen {

    private final Screen parent;

    private final SpruceOption doubleHotbarToggle;
    private final SpruceOption betterMountHudToggle;

    public configScreen(@Nullable Screen parent) {
        super(Text.literal("Armorhud test GUI"));
        this.parent = parent;

        this.doubleHotbarToggle = new SpruceBooleanOption("Double hotbar", () -> config.DOUBLE_HOTBAR, newValue -> config.DOUBLE_HOTBAR = newValue, Text.literal("Toggles double hotbar config"));
        this.betterMountHudToggle = new SpruceBooleanOption("Better mount HUD", () -> config.BETTER_MOUNT_HUD, newValue -> config.BETTER_MOUNT_HUD = newValue, Text.literal("Toggles the better mount hud config"));
    }

    @Override
    protected void init() {
        super.init();

        SpruceOptionListWidget list = new SpruceOptionListWidget(Position.of(0, 34), this.width, this.height - 69);
        list.addOptionEntry(this.doubleHotbarToggle, null);
        list.addOptionEntry(this.betterMountHudToggle, null);

        this.addDrawableChild(list);

        this.addDrawableChild(new SpruceButtonWidget(Position.of(this.width / 2 - 50, this.height - 30), 100, 20, Text.literal("Done"), button -> this.applyChanges()));
    }

    @Override
    public void renderTitle(DrawContext context, int MouseX, int MouseY, float delta) {
        context.drawCenteredTextWithShadow(this.textRenderer, this.title, this.width / 2, 8, 16777215);
    }

    public void applyChanges() {
        config config = armorHud.CONFIG;
        Properties properties = new Properties();
        config.write(properties);
        config.save();
        this.client.setScreen(parent);
    }

}
```

This will show the dirt top and bottom bars if you aren't in a world, but won't show them in game. I'm sorry if the solution is very simple, I'm trying to make a mod that's fun for me, but I'm not that experienced in java.

**To Reproduce**
1. Download mod menu to open the option screen
2. Open the screen from the title screen, everything seems fine
3. Open the screen from a world, the top and bottom bars have suddenly dissappeared

**Expected behavior**
It is expected that the top and bottom bars are visible in a minecraft world

**Screenshots**
![2023-10-23_14 33 29](https://github.com/LambdAurora/SpruceUI/assets/50689727/847c41ba-8c0f-4e4f-8716-1922c2e05935)
![2023-10-23_14 33 38](https://github.com/LambdAurora/SpruceUI/assets/50689727/8130c728-979a-4c07-83bf-2f41122ef6ff)

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.5.2
 - Minecraft: 1.20.2
 - Fabric: 0.14.23
 - Mods: modmenu 8.0.0
 - Version: 5.0.3+1.20.2
 - Branch: 1.20.2

**Comment by LambdAurora** [comment]
This is caused by the default behavior of Minecraft's `Screen#renderBackground` which is defined as a method that a method that calls `fillGradient` if the client world isn't `null`, or draws the background texture otherwise.

To fix this issue you can add this to your class:
```java
    @Override
    public void renderBackground(DrawContext context) {
        this.renderBackgroundTexture(context);
    }
```

Names might need adaptation if different in your mappings, but this is the general idea.

**Comment by legoraft** [comment]
Where would I add this? If I add it in the class, it just shows up as an error

**Comment by LambdAurora** [comment]
I'm guessing you're using yarn mappings?

**Comment by legoraft** [comment]
yes

**Comment by LambdAurora** [comment]
My bad, I've missed some method arguments:
```java
@Override
public void renderBackground(DrawContext context, int mouseX, int mouseY, float delta) {
    this.renderBackgroundTexture(context);
}
```

**Comment by legoraft** [comment]
ah yes, thank you. But I do need to call it somewhere right?

**Comment by legoraft** [comment]
Oh no, isn't necessary, it works just fine. Thanks a lot!
